% integral_uncertainty_propagation.m — Propagate INTEGRAL state uncertainty.
% The script detects apsides and independently compares LinCov, UT, and Monte Carlo propagation.
% Author: Pasquale Marzaioli

clear;
close all;
clc;

% Resolve modular helpers relative to this script rather than the working directory.
addpath(fullfile(fileparts(mfilename("fullpath")), "functions"));

%% Configuration and initial estimate

muEarth = 398600.4418; % km^3/s^2
initialEpoch = datetime(2025, 10, 26, 1, 10, 57, 769, ...
    "TimeZone", "UTC", "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS");
initialMean = [7896.37847595; -3152.23575783; 149961.25963557; ...
              -0.6035374932; 0.0159618300; 0.0321154658];
initialCovariance = [6.7e-3, -2.1e-3,  7.6e-4, 0, 0, 0; ...
                    -2.1e-3, 9.7e-3,  5.3e-4, 0, 0, 0; ...
                     7.6e-4, 5.3e-4,  2.1e-3, 0, 0, 0; ...
                     0,       0,       0,       4.7e-7, 0, 0; ...
                     0,       0,       0,       0, 3.1e-7, 0; ...
                     0,       0,       0,       0, 0, 1.6e-7];

numberOfApsides = 5;
numberOfMonteCarloSamples = 2000;
stabilityToleranceSigma = 0.05;
randomSeed = 42;
saveFigures = true;
figureDirectory = "plots";

integratorOptions = odeset("RelTol", 1e-12, "AbsTol", 1e-13);

%% Detect the next five pericentres and apocentres

initialRadius = norm(initialMean(1:3));
initialSpeedSquared = dot(initialMean(4:6), initialMean(4:6));
semimajorAxis = 1 / (2 / initialRadius - initialSpeedSquared / muEarth);
orbitalPeriod = 2 * pi * sqrt(semimajorAxis^3 / muEarth);

eventOptions = odeset(integratorOptions, "Events", ...
    @(time, state) apsisEvent(time, state, muEarth));
propagationDuration = (numberOfApsides + 0.1) * orbitalPeriod;
[~, ~, eventTimes, eventStates] = ode113( ...
    @(time, state) twoBodyDynamics(time, state, muEarth), ...
    [0, propagationDuration], initialMean, eventOptions);

% Ignore a possible root at the supplied initial apocentre, then classify
% each later root through the time derivative of r dot v at the event.
validEvents = eventTimes > 1;
eventTimes = eventTimes(validEvents);
eventStates = eventStates(validEvents, :);
radialTurningDerivative = sum(eventStates(:, 4:6).^2, 2) ...
    - muEarth ./ vecnorm(eventStates(:, 1:3), 2, 2);
pericentreMask = radialTurningDerivative > 0;
apocentreMask = radialTurningDerivative < 0;

pericentreTimes = eventTimes(pericentreMask);
pericentreStates = eventStates(pericentreMask, :).';
apocentreTimes = eventTimes(apocentreMask);
apocentreStates = eventStates(apocentreMask, :).';

assert(numel(pericentreTimes) >= numberOfApsides, ...
    "Fewer than five pericentre events were detected.");
assert(numel(apocentreTimes) >= numberOfApsides, ...
    "Fewer than five apocentre events were detected.");
pericentreTimes = pericentreTimes(1:numberOfApsides);
pericentreStates = pericentreStates(:, 1:numberOfApsides);
apocentreTimes = apocentreTimes(1:numberOfApsides);
apocentreStates = apocentreStates(:, 1:numberOfApsides);

pericentreEpochs = initialEpoch + seconds(pericentreTimes);
apocentreEpochs = initialEpoch + seconds(apocentreTimes);
fprintf("Detected apsides for five revolutions (Keplerian period %.3f s).\n", orbitalPeriod);
printStateTable(pericentreEpochs, pericentreStates, "Pericentre");
printStateTable(apocentreEpochs, apocentreStates, "Apocentre");

%% Linearized covariance propagation using the STM (LinCov)

[targetTimes, targetOrder] = sort([pericentreTimes; apocentreTimes]);
pericentreTargetIndices = find(targetOrder <= numberOfApsides);
apocentreTargetIndices = find(targetOrder > numberOfApsides);

initialAugmentedState = [initialMean; reshape(eye(6), 36, 1)];
[~, augmentedHistory] = ode113( ...
    @(time, state) variationalDynamics(time, state, muEarth), ...
    [0; targetTimes], initialAugmentedState, integratorOptions);
augmentedHistory = augmentedHistory(2:end, :).';

linearMeans = augmentedHistory(1:6, :);
linearCovariances = zeros(6, 6, numel(targetTimes));
for epochIndex = 1:numel(targetTimes)
    stateTransitionMatrix = reshape(augmentedHistory(7:end, epochIndex), 6, 6);
    linearCovariances(:, :, epochIndex) = symmetrize( ...
        stateTransitionMatrix * initialCovariance * stateTransitionMatrix.');
end

%% Unscented-transform propagation

alpha = 0.1;
beta = 2;
kappa = 0;
[sigmaPoints, meanWeights, covarianceWeights] = unscentedSigmaPoints( ...
    initialMean, initialCovariance, alpha, beta, kappa);

% Verify that cancellation from the scaled negative weights still reproduces
% the prescribed first two moments at machine precision.
reconstructedMean = sigmaPoints * meanWeights;
centeredInitialSigmaPoints = sigmaPoints - reconstructedMean;
reconstructedCovariance = (centeredInitialSigmaPoints .* covarianceWeights.') ...
    * centeredInitialSigmaPoints.';
componentScales = sqrt(diag(initialCovariance));
normalizedCovarianceError = (reconstructedCovariance - initialCovariance) ./ ...
    (componentScales * componentScales.');
assert(max(abs(reconstructedMean - initialMean) ./ max(abs(initialMean), 1)) < 1e-12, ...
    "UT sigma points do not reconstruct the initial mean accurately.");
assert(max(abs(normalizedCovarianceError), [], "all") < 1e-8, ...
    "UT sigma points do not reconstruct the initial covariance accurately.");

numberOfSigmaPoints = size(sigmaPoints, 2);
propagatedSigmaPoints = zeros(6, numel(targetTimes), numberOfSigmaPoints);
for sigmaIndex = 1:numberOfSigmaPoints
    propagatedSigmaPoints(:, :, sigmaIndex) = propagateState( ...
        sigmaPoints(:, sigmaIndex), targetTimes, muEarth, integratorOptions);
end

unscentedMeans = zeros(6, numel(targetTimes));
unscentedCovariances = zeros(6, 6, numel(targetTimes));
for epochIndex = 1:numel(targetTimes)
    epochSigmaPoints = reshape(propagatedSigmaPoints(:, epochIndex, :), 6, []);
    unscentedMeans(:, epochIndex) = epochSigmaPoints * meanWeights;
    centeredSigmaPoints = epochSigmaPoints - unscentedMeans(:, epochIndex);
    unscentedCovariances(:, :, epochIndex) = symmetrize( ...
        (centeredSigmaPoints .* covarianceWeights.') * centeredSigmaPoints.');
end

%% Monte Carlo propagation and retrospective mean stability

rng(randomSeed, "twister");
initialSquareRoot = chol(initialCovariance, "lower");
initialSamples = initialMean + initialSquareRoot * ...
    randn(6, numberOfMonteCarloSamples);
propagatedSamples = zeros(6, numel(targetTimes), numberOfMonteCarloSamples);

fprintf("Propagating %d independent Monte Carlo samples...\n", ...
    numberOfMonteCarloSamples);
progressStep = max(1, floor(numberOfMonteCarloSamples / 10));
for sampleIndex = 1:numberOfMonteCarloSamples
    propagatedSamples(:, :, sampleIndex) = propagateState( ...
        initialSamples(:, sampleIndex), targetTimes, muEarth, integratorOptions);
    if mod(sampleIndex, progressStep) == 0
        fprintf("  Monte Carlo progress: %d/%d\n", ...
            sampleIndex, numberOfMonteCarloSamples);
    end
end
assert(all(isfinite(propagatedSamples), "all"), ...
    "Monte Carlo propagation produced a non-finite state.");

monteCarloMeans = zeros(6, numel(targetTimes));
monteCarloCovariances = zeros(6, 6, numel(targetTimes));
for epochIndex = 1:numel(targetTimes)
    epochSamples = reshape(propagatedSamples(:, epochIndex, :), 6, []);
    monteCarloMeans(:, epochIndex) = mean(epochSamples, 2);
    monteCarloCovariances(:, :, epochIndex) = cov(epochSamples.');
end

finalPericentreSamples = reshape( ...
    propagatedSamples(:, pericentreTargetIndices(end), :), 6, []);
finalApocentreSamples = reshape( ...
    propagatedSamples(:, apocentreTargetIndices(end), :), 6, []);
sampleCount = 1:numberOfMonteCarloSamples;
pericentreCumulativeMean = cumsum(finalPericentreSamples, 2) ./ sampleCount;
apocentreCumulativeMean = cumsum(finalApocentreSamples, 2) ./ sampleCount;

% Measure retrospective stability against the same run's final sample mean;
% this is descriptive and is not an independent convergence proof.
pericentreScale = max(std(finalPericentreSamples, 0, 2), eps);
apocentreScale = max(std(finalApocentreSamples, 0, 2), eps);
pericentreNormalizedError = max(abs(pericentreCumulativeMean ...
    - pericentreCumulativeMean(:, end)) ./ pericentreScale, [], 1);
apocentreNormalizedError = max(abs(apocentreCumulativeMean ...
    - apocentreCumulativeMean(:, end)) ./ apocentreScale, [], 1);
remainingNormalizedError = fliplr(cummax(fliplr(max( ...
    pericentreNormalizedError, apocentreNormalizedError))));
minimumStableSampleCount = find( ...
    remainingNormalizedError <= stabilityToleranceSigma, 1);
fprintf("Relative to the full sample, Monte Carlo means remain within " + ...
    "%.3f sigma after N = %d samples.\n", ...
    stabilityToleranceSigma, minimumStableSampleCount);

%% Transform results to the local RTH frames

linearPericentreMeans = linearMeans(:, pericentreTargetIndices);
linearApocentreMeans = linearMeans(:, apocentreTargetIndices);
unscentedPericentreMeans = unscentedMeans(:, pericentreTargetIndices);
unscentedApocentreMeans = unscentedMeans(:, apocentreTargetIndices);

linearPericentreCovariances = linearCovariances(:, :, pericentreTargetIndices);
linearApocentreCovariances = linearCovariances(:, :, apocentreTargetIndices);
unscentedPericentreCovariances = unscentedCovariances(:, :, pericentreTargetIndices);
unscentedApocentreCovariances = unscentedCovariances(:, :, apocentreTargetIndices);
monteCarloPericentreCovariances = monteCarloCovariances(:, :, pericentreTargetIndices);
monteCarloApocentreCovariances = monteCarloCovariances(:, :, apocentreTargetIndices);

[pericentreFrames, linearPericentreCovariancesRth, ...
    unscentedPericentreCovariancesRth, monteCarloPericentreCovariancesRth] = ...
    transformCovarianceSeries(linearPericentreMeans, ...
    linearPericentreCovariances, unscentedPericentreCovariances, ...
    monteCarloPericentreCovariances);
[apocentreFrames, linearApocentreCovariancesRth, ...
    unscentedApocentreCovariancesRth, monteCarloApocentreCovariancesRth] = ...
    transformCovarianceSeries(linearApocentreMeans, ...
    linearApocentreCovariances, unscentedApocentreCovariances, ...
    monteCarloApocentreCovariances);

pericentreMeanDifferenceRth = transformMeanDifference( ...
    unscentedPericentreMeans - linearPericentreMeans, pericentreFrames);
apocentreMeanDifferenceRth = transformMeanDifference( ...
    unscentedApocentreMeans - linearApocentreMeans, apocentreFrames);

%% Physical and numerical verification

pericentreSpacingError = max(abs(diff(pericentreTimes) - orbitalPeriod));
apocentreSpacingError = max(abs(diff(apocentreTimes) - orbitalPeriod));
assert(pericentreSpacingError < 0.1, ...
    "Pericentre spacing is inconsistent with the Keplerian period.");
assert(apocentreSpacingError < 0.1, ...
    "Apocentre spacing is inconsistent with the Keplerian period.");

allNominalStates = [pericentreStates, apocentreStates];
specificEnergy = vecnorm(allNominalStates(4:6, :), 2, 1).^2 / 2 ...
    - muEarth ./ vecnorm(allNominalStates(1:3, :), 2, 1);
referenceEnergy = initialSpeedSquared / 2 - muEarth / initialRadius;
relativeEnergyDrift = max(abs((specificEnergy - referenceEnergy) / referenceEnergy));
assert(relativeEnergyDrift < 1e-10, ...
    "Specific orbital energy was not conserved to the requested tolerance.");

initialAngularMomentum = cross(initialMean(1:3), initialMean(4:6));
eventAngularMomentum = cross(allNominalStates(1:3, :), allNominalStates(4:6, :));
relativeAngularMomentumDrift = max(vecnorm( ...
    eventAngularMomentum - initialAngularMomentum, 2, 1)) ...
    / norm(initialAngularMomentum);
assert(relativeAngularMomentumDrift < 1e-10, ...
    "Specific angular momentum was not conserved to the requested tolerance.");

eccentricityVector = cross(initialMean(4:6), initialAngularMomentum) / muEarth ...
    - initialMean(1:3) / initialRadius;
eccentricity = norm(eccentricityVector);
expectedPericentreRadius = semimajorAxis * (1 - eccentricity);
expectedApocentreRadius = semimajorAxis * (1 + eccentricity);
assert(abs(norm(pericentreStates(1:3, 1)) - expectedPericentreRadius) < 1e-5, ...
    "Detected pericentre radius disagrees with the analytic two-body value.");
assert(abs(norm(apocentreStates(1:3, 1)) - expectedApocentreRadius) < 1e-5, ...
    "Detected apocentre radius disagrees with the analytic two-body value.");

firstStateTransitionMatrix = reshape(augmentedHistory(7:end, 1), 6, 6);
finiteDifferenceMatrix = finiteDifferenceStateTransition( ...
    initialMean, targetTimes(1), muEarth, integratorOptions);
relativeStmError = norm(firstStateTransitionMatrix - finiteDifferenceMatrix, "fro") ...
    / norm(finiteDifferenceMatrix, "fro");
assert(relativeStmError < 1e-5, ...
    "The variational STM disagrees with a central finite-difference check.");

assertCovarianceSeries(linearCovariances, "LinCov");
assertCovarianceSeries(unscentedCovariances, "UT");
assertCovarianceSeries(monteCarloCovariances, "Monte Carlo");
fprintf("Verification passed: max apsis-spacing error %.3g s, relative energy " + ...
    "drift %.3g, relative angular-momentum drift %.3g, STM error %.3g.\n", ...
    max(pericentreSpacingError, apocentreSpacingError), relativeEnergyDrift, ...
    relativeAngularMomentumDrift, relativeStmError);

%% Reproduce the uncertainty-propagation figures

plotMeanDifference(pericentreMeanDifferenceRth, "Pericentre", ...
    "UT minus LinCov mean at pericentres", ...
    "pericentre_mean_difference", saveFigures, figureDirectory);
plotMeanDifference(apocentreMeanDifferenceRth, "Apocentre", ...
    "UT minus LinCov mean at apocentres", ...
    "apocentre_mean_difference", saveFigures, figureDirectory);

plotStandardDeviations(linearPericentreCovariancesRth, ...
    unscentedPericentreCovariancesRth, monteCarloPericentreCovariancesRth, ...
    "Pericentre", ...
    "RTH standard deviations at pericentres", ...
    "pericentre_rth_standard_deviations", saveFigures, figureDirectory);
plotStandardDeviations(linearApocentreCovariancesRth, ...
    unscentedApocentreCovariancesRth, monteCarloApocentreCovariancesRth, ...
    "Apocentre", ...
    "RTH standard deviations at apocentres", ...
    "apocentre_rth_standard_deviations", saveFigures, figureDirectory);

plotCrossCovariances(linearPericentreCovariancesRth, ...
    unscentedPericentreCovariancesRth, monteCarloPericentreCovariancesRth, ...
    "Pericentre", ...
    "RTH cross-covariances at pericentres", ...
    "pericentre_rth_cross_covariances", saveFigures, figureDirectory);
plotCrossCovariances(linearApocentreCovariancesRth, ...
    unscentedApocentreCovariancesRth, monteCarloApocentreCovariancesRth, ...
    "Apocentre", ...
    "RTH cross-covariances at apocentres", ...
    "apocentre_rth_cross_covariances", saveFigures, figureDirectory);

plotMonteCarloStability(sampleCount, pericentreCumulativeMean, ...
    apocentreCumulativeMean, minimumStableSampleCount, ...
    "Monte Carlo mean stability", ...
    "monte_carlo_mean_convergence", saveFigures, figureDirectory);

plotMonteCarloEllipses(propagatedSamples(:, pericentreTargetIndices, :), ...
    linearPericentreMeans, unscentedPericentreMeans, ...
    monteCarloMeans(:, pericentreTargetIndices), ...
    linearPericentreCovariances, unscentedPericentreCovariances, ...
    monteCarloPericentreCovariances, pericentreFrames, "Pericentre", ...
    "Monte Carlo distributions at pericentres", ...
    "pericentre_monte_carlo_distributions", saveFigures, figureDirectory);
plotMonteCarloEllipses(propagatedSamples(:, apocentreTargetIndices, :), ...
    linearApocentreMeans, unscentedApocentreMeans, ...
    monteCarloMeans(:, apocentreTargetIndices), ...
    linearApocentreCovariances, unscentedApocentreCovariances, ...
    monteCarloApocentreCovariances, apocentreFrames, "Apocentre", ...
    "Monte Carlo distributions at apocentres", ...
    "apocentre_monte_carlo_distributions", saveFigures, figureDirectory);

plotMaximumCovarianceAxes(linearPericentreCovariances, ...
    unscentedPericentreCovariances, monteCarloPericentreCovariances, ...
    linearApocentreCovariances, unscentedApocentreCovariances, ...
    monteCarloApocentreCovariances, "Maximum covariance axes", ...
    "maximum_covariance_axes", saveFigures, figureDirectory);
